[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
