// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgkntfsxbeyunxfpwabh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZna250ZnN4YmV5dW54ZnB3YWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTIxMTgsImV4cCI6MjA3MjQyODExOH0.HUioWFo5kT3CMQNDpI9nY-6MO1FGN84jp07GMhAULvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});